import { redirect } from "next/navigation";
import { Parser } from "json2csv";
import * as Constants from "@/lib/constants";
import { createMetrics } from "@/modules/metrics/services/server/MetricTracker";
import { getAll } from "@/utils/api/server/RowsApi";
import UrlUtils from "@/utils/app/UrlUtils";
import ApiHelper from "@/lib/helpers/ApiHelper";
import { getEntityPermission } from "@/lib/helpers/PermissionsHelper";
import { verifyUserHasPermission } from "@/lib/helpers/server/PermissionsService";
import RowsRequestUtils from "../utils/RowsRequestUtils";
import { IServerComponentsProps } from "@/lib/dtos/ServerComponentsProps";
import { headers } from "next/headers";

export const loader = async (props: IServerComponentsProps) => {
  const params = (await props.params) || {};
  const headersList = await headers();
  const request = new Request("http://localhost", {
    headers: headersList,
  });
  const { time, getServerTimingHeader } = await createMetrics({ request, params }, `[Rows_Export] ${params?.entity}`);
  const { t, userId, tenantId, entity } = await RowsRequestUtils.getLoader({ request, params: props.params });
  await time(verifyUserHasPermission(getEntityPermission(entity, "view"), tenantId), "verifyUserHasPermission");
  if (!entity.isAutogenerated || entity.type === "system") {
    throw redirect(tenantId ? UrlUtils.currentTenantUrl(params ?? {}, "404") : "/404");
  }
  const rowsData = await time(
    getAll({
      entity,
      tenantId,
      userId,
      urlSearchParams: new URL(request.url).searchParams,
      pageSize: Constants.MAX_EXPORT_PAGE_SIZE,
      time,
    }),
    "getAll"
  );
  const apiFormat = rowsData.items.map((item) => {
    return ApiHelper.getApiFormat(entity, item);
  });
  const parser = new Parser({ fields: entity.properties.map((f) => f.name), delimiter: "|" });
  const csv = parser.parse(apiFormat);
  return new Response(csv, {
    status: 200,
    headers: {
      "Content-Type": "text/csv",
      "Content-Disposition": `attachment; filename=${t(entity.titlePlural)}.csv`,
      ...getServerTimingHeader(),
    },
  });
};

