import { EntityTag } from "@prisma/client";
import { redirect } from "next/navigation";
import { MetaTagsDto } from "@/lib/dtos/seo/MetaTagsDto";
import { Colors } from "@/lib/enums/shared/Colors";
import { Routes, getNoCodeRoutes } from "@/utils/api/server/EntitiesApi";
import { GetRowData, get } from "@/utils/api/server/RowsApi";
import UrlUtils from "@/utils/app/UrlUtils";
import RowHelper from "@/lib/helpers/RowHelper";
import RowsRequestUtils from "../utils/RowsRequestUtils";
import { CustomError } from "@/lib/dtos/shared/CustomError";
import { IServerComponentsProps } from "@/lib/dtos/ServerComponentsProps";
import { db } from "@/db";
import { headers } from "next/headers";

export type LoaderData = {
  meta: MetaTagsDto;
  rowData: GetRowData;
  routes: Routes;
  tags: EntityTag[];
};
export const loader = async (props: IServerComponentsProps) => {
  const params = (await props.params) || {};
  const headersList = await headers();
  const url = headersList.get("x-url") || headersList.get("referer") || "http://localhost";
  const request = new Request(url, {
    headers: headersList,
  });    
  const { t, userId, tenantId, entity } = await RowsRequestUtils.getLoader({ request, params: props.params });
  if (!entity.isAutogenerated || entity.type === "system") {
    throw redirect(tenantId ? UrlUtils.currentTenantUrl(params, "404") : "/404");
  }
  const rowData = await get(params.id!, {
    entity,
    tenantId,
    userId,
  });
  if (!rowData.rowPermissions.canUpdate) {
    throw Response.json(new CustomError("You can't update this row", { permissions: rowData.rowPermissions }), { status: 403 });
  }
  const data: LoaderData = {
    meta: [{ title: `${t("shared.tag")} | ${RowHelper.getTextDescription({ entity, item: rowData.item, t })} | ${process.env.APP_NAME}` }],
    rowData,
    tags: await db.entityTags.getEntityTags(entity.id),
    routes: getNoCodeRoutes({ request, params }),
  };
  return Response.json(data);
};

const badRequest = (data: { error: string }) => Response.json(data, { status: 400 });
export const action = async (props: IServerComponentsProps) => {
  const params = (await props.params) || {};
  const headersList = await headers();
  const url = headersList.get("x-url") || headersList.get("referer") || "http://localhost";
  const request = new Request(url, {
    headers: headersList,
  });    
  const { t, userId, tenantId, entity, form } = await RowsRequestUtils.getAction({ request, params: props.params });
  const rowData = await get(params.id!, {
    entity,
    tenantId,
    userId,
  });
  const action = form.get("action");
  const { item } = rowData;
  if (!rowData.rowPermissions.canUpdate) {
    throw Response.json(new CustomError("You can't update this row", { permissions: rowData.rowPermissions }), { status: 403 });
  }
  if (action === "new-tag") {
    const value = form.get("tag-name")?.toString() ?? "";
    const color = Number(form.get("tag-color") ?? Colors.INDIGO);
    let tag = await db.entityTags.getEntityTag(entity.id, value);
    if (!tag) {
      tag = await db.entityTags.createEntityTag({
        entityId: entity.id,
        value,
        color,
      });
    }
    const existingTag = await db.rowTags.getRowTag(item.id, value);
    if (tag && !existingTag) {
      await db.rowTags.createRowTag({
        rowId: item.id,
        tagId: tag.id,
      });
    }
    return Response.json({});
  } else if (action === "edit-tag") {
    const id = form.get("tag-id")?.toString() ?? "";
    const value = form.get("tag-name")?.toString() ?? "";
    const color = Number(form.get("tag-color"));
    await db.entityTags.updateEntityTag(id, {
      value,
      color,
    });
    return Response.json({});
  } else if (action === "set-tag") {
    const id = form.get("tag-id")?.toString() ?? "";
    const tagAction = form.get("tag-action")?.toString() ?? "";
    if (tagAction === "add") {
      await db.rowTags.createRowTag({
        rowId: item.id,
        tagId: id,
      });
    } else {
      await db.rowTags.deleteRowTags(item.id, id);
    }
    return Response.json({});
  } else if (action === "delete-tag") {
    const id = form.get("tag-id")?.toString() ?? "";
    const tag = await db.entityTags.getEntityTagById(id);
    if (tag) {
      await db.entityTags.deleteEntityTag(tag.id);
    }
    return Response.json({});
  } else {
    return badRequest({ error: t("shared.invalidForm") });
  }
};

