import { Tenant } from "@prisma/client";
import { redirect } from "next/navigation";
import { MetaTagsDto } from "@/lib/dtos/seo/MetaTagsDto";
import { RowAccess } from "@/lib/enums/entities/RowAccess";
import { Routes, getNoCodeRoutes } from "@/utils/api/server/EntitiesApi";
import { share, setAccess, del } from "@/utils/api/server/RowPermissionsApi";
import { GetRowData, get } from "@/utils/api/server/RowsApi";
import UrlUtils from "@/utils/app/UrlUtils";
import { UserWithDetailsDto } from "@/db/models/accounts/UsersModel";
import RowHelper from "@/lib/helpers/RowHelper";
import RowsRequestUtils from "../utils/RowsRequestUtils";
import EventsService from "@/modules/events/services/.server/EventsService";
import { RowSharedDto } from "@/modules/events/dtos/RowSharedDto";
import { IServerComponentsProps } from "@/lib/dtos/ServerComponentsProps";
import { db } from "@/db";

export type LoaderData = {
  meta: MetaTagsDto;
  rowData: GetRowData;
  routes: Routes;
  tenants: Tenant[];
  users: UserWithDetailsDto[];
};
export const loader = async (props: IServerComponentsProps) => {
  const params = (await props.params) || {};
  const request = props.request!;    
  const { t, userId, tenantId, entity } = await RowsRequestUtils.getLoader({ request, params: props.params });
  if (!entity.isAutogenerated || entity.type === "system") {
    throw redirect(tenantId ? UrlUtils.currentTenantUrl(params, "404") : "/404");
  }
  const rowData = await get(params.id!, {
    entity,
    tenantId,
    userId,
  });
  if (rowData.item.createdByUserId !== userId) {
    const user = await db.users.getUser(userId);
    if (!user?.admin) {
      throw Error(t("shared.unauthorized"));
    }
  }
  let tenants: Tenant[] = [];
  if (tenantId) {
    tenants.push((await db.tenants.getTenant(tenantId))!);
  } else {
    tenants = await db.tenants.adminGetAllTenants();
  }
  const data: LoaderData = {
    meta: [{ title: `${t("shared.share")} | ${RowHelper.getTextDescription({ entity, item: rowData.item, t })} | ${process.env.APP_NAME}` }],
    rowData,
    routes: getNoCodeRoutes({ request, params }),
    tenants,
    users: (await db.users.getUsersByTenant(tenantId)).filter((f) => f.id !== userId),
  };
  return Response.json(data);
};

export const action = async (props: IServerComponentsProps) => {
  const params = (await props.params) || {};
  const request = props.request!;    
  const { t, entity, tenantId, userId, form } = await RowsRequestUtils.getAction({ request, params: props.params });
  const user = await db.users.getUser(userId);
  if (!user) {
    throw redirect(tenantId ? UrlUtils.currentTenantUrl(params, "404") : "/404");
  }

  const action = form.get("action");
  if (!entity.isAutogenerated || entity.type === "system") {
    throw redirect(tenantId ? UrlUtils.currentTenantUrl(params, "404") : "/404");
  }
  const rowData = await get(params.id!, {
    entity,
    tenantId,
    userId,
  });

  if (action === "share") {
    const type = form.get("type")?.toString() as "tenant" | "user" | "role" | "group" | "public";
    const id = form.get("id")?.toString() ?? "";
    const access = form.get("access")?.toString() as RowAccess;
    try {
      await share(rowData.item, {
        type,
        id,
        access,
      });
      await EventsService.create({
        request,
        event: "row.shared",
        tenantId,
        userId,
        data: {
          id: rowData.item.id,
          title: RowHelper.getTextDescription({ entity, item: rowData.item, t }),
          entity: { id: entity.id, name: entity.name, slug: entity.slug, title: entity.title },
          type,
          to: id,
          access,
          user: { id: user.id, email: user.email },
        } satisfies RowSharedDto,
      });
      return Response.json({ success: t("shared.saved") });
    } catch (error: any) {
      return Response.json({ error: error.message }, { status: 400 });
    }
  } else if (action === "set-access") {
    const id = form.get("id")?.toString() ?? "";
    const access = form.get("access")?.toString() as RowAccess;
    await setAccess(id, access);
    return Response.json({ success: t("shared.saved") });
  } else if (action === "remove") {
    const id = form.get("id")?.toString() ?? "";
    await del(id);
    return Response.json({ success: t("shared.deleted") });
  } else {
    return Response.json({ error: t("shared.invalidForm") }, { status: 400 });
  }
};

