import { defaultAppConfiguration } from "@/modules/core/data/defaultAppConfiguration";

import { IAppConfigurationDb } from "./interfaces/core/IAppConfigurationDb";
import { AppConfigurationDbPrisma } from "./repositories/prisma/AppConfigurationDbPrisma";
import { IUsersDb } from "./interfaces/accounts/IUsersDb";
import { UsersDbPrisma } from "./repositories/prisma/UsersDbPrisma";
import { ITenantUserDb } from "./interfaces/accounts/ITenantUserDb";
import { TenantUserDbPrisma } from "./repositories/prisma/TenantUserDbPrisma";
import { IUserRegistrationAttemptDb } from "./interfaces/accounts/IUserRegistrationAttemptDb";
import { UserRegistrationAttemptDbPrisma } from "./repositories/prisma/UserRegistrationAttemptDbPrisma";
import { ITenantIpAddressDb } from "./interfaces/accounts/ITenantIpAddressDb";
import { TenantIpAddressDbPrisma } from "./repositories/prisma/TenantIpAddressDbPrisma";

// TheRock Additions
import { IWorkflowsDb } from "./interfaces/workflows/IWorkflowsDb";
import { WorkflowsDbPrisma } from "./repositories/prisma/WorkflowsDbPrisma";
import { IWorkflowVariableDb } from "./interfaces/workflows/IWorkflowVariableDb";
import { WorkflowVariableDbPrisma } from "./repositories/prisma/WorkflowVariableDbPrisma";
import { IWorkflowExecutionsDb } from "./interfaces/workflows/IWorkflowExecutionsDb";
import { WorkflowExecutionsDbPrisma } from "./repositories/prisma/WorkflowExecutionsDbPrisma";
import { IWorkflowCredentialsDb } from "./interfaces/workflows/IWorkflowCredentialsDb";
import { WorkflowCredentialsDbPrisma } from "./repositories/prisma/WorkflowCredentialsDbPrisma";
import { IWorkflowBlocksDb } from "./interfaces/workflows/IWorkflowBlocksDb";
import { WorkflowBlocksDbPrisma } from "./repositories/prisma/WorkflowBlocksDbPrisma";
import { IPropertiesDb } from "./interfaces/entityBuilder/IPropertiesDb";
import { PropertiesDbPrisma } from "./repositories/prisma/PropertiesDbPrisma";
import { IFormulaLogsDb } from "./interfaces/entityBuilder/IFormulaLogsDb";
import { FormulaLogsDbPrisma } from "./repositories/prisma/FormulaLogsDbPrisma";
import { IEntityViewsDb } from "./interfaces/entityBuilder/IEntityViewsDb";
import { EntityViewsDbPrisma } from "./repositories/prisma/EntityViewsDbPrisma";
import { IRowTasksDb } from "./interfaces/entityBuilder/IRowTasksDb";
import { RowTasksDbPrisma } from "./repositories/prisma/RowTasksDbPrisma";
import { IEntityRelationshipsDb } from "./interfaces/entityBuilder/IEntityRelationshipsDb";
import { EntityRelationshipsDbPrisma } from "./repositories/prisma/EntityRelationshipsDbPrisma";
import { IFormulasDb } from "./interfaces/entityBuilder/IFormulasDb";
import { FormulasDbPrisma } from "./repositories/prisma/FormulasDbPrisma";
import { IEntityTemplatesDb } from "./interfaces/entityBuilder/IEntityTemplatesDb";
import { EntityTemplatesDbPrisma } from "./repositories/prisma/EntityTemplatesDbPrisma";
import { IEntityWebhooksDb } from "./interfaces/entityBuilder/IEntityWebhooksDb";
import { EntityWebhooksDbPrisma } from "./repositories/prisma/EntityWebhooksDbPrisma";
import { IRowCommentReactionDb } from "./interfaces/entityBuilder/IRowCommentReactionDb";
import { RowCommentReactionDbPrisma } from "./repositories/prisma/RowCommentReactionDbPrisma";
import { IEntityTagsDb } from "./interfaces/entityBuilder/IEntityTagsDb";
import { EntityTagsDbPrisma } from "./repositories/prisma/EntityTagsDbPrisma";
import { IRowsDb } from "./interfaces/entityBuilder/IRowsDb";
import { RowsDbPrisma } from "./repositories/prisma/RowsDbPrisma";
import { IRowCommentsDb } from "./interfaces/entityBuilder/IRowCommentsDb";
import { RowCommentsDbPrisma } from "./repositories/prisma/RowCommentsDbPrisma";
import { IRowRelationshipsDb } from "./interfaces/entityBuilder/IRowRelationshipsDb";
import { RowRelationshipsDbPrisma } from "./repositories/prisma/RowRelationshipsDbPrisma";
import { IRowPermissionsDb } from "./interfaces/entityBuilder/IRowPermissionsDb";
import { RowPermissionsDbPrisma } from "./repositories/prisma/RowPermissionsDbPrisma";
import { IRowTagsDb } from "./interfaces/entityBuilder/IRowTagsDb";
import { RowTagsDbPrisma } from "./repositories/prisma/RowTagsDbPrisma";
import { IGroupsDb } from "./interfaces/permissions/IGroupsDb";
import { GroupsDbPrisma } from "./repositories/prisma/GroupsDbPrisma";
import { IEntitiesDb } from "./interfaces/entityBuilder/IEntitiesDb";
import { EntitiesDbPrisma } from "./repositories/prisma/EntitiesDbPrisma";
import { IEntityGroupsDb } from "./interfaces/entityBuilder/IEntityGroupsDb";
import { EntityGroupsDbPrisma } from "./repositories/prisma/EntityGroupsDbPrisma";
import { IFeatureFlagsDb } from "./interfaces/featureFlags/IFeatureFlagsDb";
import { FeatureFlagsDbPrisma } from "./repositories/prisma/FeatureFlagsDbPrisma";
import { IBlogDb } from "./interfaces/blog/IBlogDb";
import { BlogDbPrisma } from "./repositories/prisma/BlogDbPrisma";
import { IBlogTagsDb } from "./interfaces/blog/IBlogTagsDb";
import { BlogTagsDbPrisma } from "./repositories/prisma/BlogTagsDbPrisma";
import { IBlogCategoriesDb } from "./interfaces/blog/IBlogCategoriesDb";
import { BlogCategoriesDbPrisma } from "./repositories/prisma/BlogCategoriesDbPrisma";
import { IFeedbackDb } from "./interfaces/helpDesk/IFeedbackDb";
import { FeedbackDbPrisma } from "./repositories/prisma/FeedbackDbPrisma";
import { ISurveysDb } from "./interfaces/helpDesk/ISurveysDb";
import { SurveysDbPrisma } from "./repositories/prisma/SurveysDbPrisma";
import { ISurveySubmissionsDb } from "./interfaces/helpDesk/ISurveySubmissionsDb";
import { SurveySubmissionsDbPrisma } from "./repositories/prisma/SurveySubmissionsDbPrisma";
import { IEventsDb } from "./interfaces/events/IEventsDb";
import { EventsDbPrisma } from "./repositories/prisma/EventsDbPrisma";
import { IEventWebhookAttemptsDb } from "./interfaces/events/IEventWebhookAttemptsDb";
import { EventWebhookAttemptsDbPrisma } from "./repositories/prisma/EventWebhookAttemptsDbPrisma";
import { IOnboardingSessionStepsDb } from "./interfaces/onboarding/IOnboardingSessionStepsDb";
import { OnboardingSessionStepsDbPrisma } from "./repositories/prisma/OnboardingSessionStepsDbPrisma";
import { IOnboardingDb } from "./interfaces/onboarding/IOnboardingDb";
import { OnboardingDbPrisma } from "./repositories/prisma/OnboardingDbPrisma";
import { IOnboardingSessionsDb } from "./interfaces/onboarding/IOnboardingSessionsDb";
import { OnboardingSessionsDbPrisma } from "./repositories/prisma/OnboardingSessionsDbPrisma";
import { IKbCategoriesDb } from "./interfaces/knowledgebase/IKbCategoriesDb";
import { KbCategoriesDbPrisma } from "./repositories/prisma/KbCategoriesDbPrisma";
import { IKbCategorySectionsDb } from "./interfaces/knowledgebase/IKbCategorySectionsDb";
import { KbCategorySectionsDbPrisma } from "./repositories/prisma/KbCategorySectionsDbPrisma";
import { IKnowledgeBaseDb } from "./interfaces/knowledgebase/IKnowledgeBaseDb";
import { KnowledgeBaseDbPrisma } from "./repositories/prisma/KnowledgeBaseDbPrisma";
import { IKbAnalyticsDb } from "./interfaces/knowledgebase/IKbAnalyticsDb";
import { KbAnalyticsDbPrisma } from "./repositories/prisma/KbAnalyticsDbPrisma";
import { IKbArticlesDb } from "./interfaces/knowledgebase/IKbArticlesDb";
import { KbArticlesDbPrisma } from "./repositories/prisma/KbArticlesDbPrisma";
import { ITenantTypesDb } from "./interfaces/accounts/ITenantTypesDb";
import { TenantTypesDbPrisma } from "./repositories/prisma/TenantTypesDbPrisma";
import { ITenantSubscriptionProductsDb } from "./interfaces/accounts/ITenantSubscriptionProductsDb";
import { TenantSubscriptionProductsDbPrisma } from "./repositories/prisma/TenantSubscriptionProductsDbPrisma";
import { IRegistrationDb } from "./interfaces/accounts/IRegistrationDb";
import { RegistrationDbPrisma } from "./repositories/prisma/RegistrationDbPrisma";
import { ITenantInboundAddressesDb } from "./interfaces/accounts/ITenantInboundAddressesDb";
import { TenantInboundAddressesDbPrisma } from "./repositories/prisma/TenantInboundAddressesDbPrisma";
import { IBlacklistDb } from "./interfaces/accounts/IBlacklistDb";
import { BlacklistDbPrisma } from "./repositories/prisma/BlacklistDbPrisma";
import { ITenantSubscriptionsDb } from "./interfaces/subscriptions/ITenantSubscriptionsDb";
import { TenantSubscriptionsDbPrisma } from "./repositories/prisma/TenantSubscriptionsDbPrisma";
import { IUserGroupsDb } from "./interfaces/accounts/IUserGroupsDb";
import { UserGroupsDbPrisma } from "./repositories/prisma/UserGroupsDbPrisma";
import { ITenantUserInvitationsDb } from "./interfaces/accounts/ITenantUserInvitationsDb";
import { TenantUserInvitationsDbPrisma } from "./repositories/prisma/TenantUserInvitationsDbPrisma";
import { ITenantsDb } from "./interfaces/accounts/ITenantsDb";
import { TenantsDbPrisma } from "./repositories/prisma/TenantsDbPrisma";
import { IPageBlocksDb } from "./interfaces/pageBlocks/IPageBlocksDb";
import { PageBlocksDbPrisma } from "./repositories/prisma/PageBlocksDbPrisma";
import { IPageMetaTagsDb } from "./interfaces/pageBlocks/IPageMetaTagsDb";
import { PageMetaTagsDbPrisma } from "./repositories/prisma/PageMetaTagsDbPrisma";
import { IPagesDb } from "./interfaces/pageBlocks/IPagesDb";
import { PagesDbPrisma } from "./repositories/prisma/PagesDbPrisma";
import { IPromptFlowGroupsDb } from "./interfaces/promptFlows/IPromptFlowGroupsDb";
import { PromptFlowGroupsDbPrisma } from "./repositories/prisma/PromptFlowGroupsDbPrisma";
import { IPromptFlowOutputsDb } from "./interfaces/promptFlows/IPromptFlowOutputsDb";
import { PromptFlowOutputsDbPrisma } from "./repositories/prisma/PromptFlowOutputsDbPrisma";
import { IPromptExecutionsDb } from "./interfaces/promptFlows/IPromptExecutionsDb";
import { PromptExecutionsDbPrisma } from "./repositories/prisma/PromptExecutionsDbPrisma";
import { IPromptFlowsDb } from "./interfaces/promptFlows/IPromptFlowsDb";
import { PromptFlowsDbPrisma } from "./repositories/prisma/PromptFlowsDbPrisma";
import { IPromptFlowInputVariablesDb } from "./interfaces/promptFlows/IPromptFlowInputVariablesDb";
import { PromptFlowInputVariablesDbPrisma } from "./repositories/prisma/PromptFlowInputVariablesDbPrisma";
import { IPromptFlowOutputMappingsDb } from "./interfaces/promptFlows/IPromptFlowOutputMappingsDb";
import { PromptFlowOutputMappingsDbPrisma } from "./repositories/prisma/PromptFlowOutputMappingsDbPrisma";
import { IOutboundEmailsDb } from "./interfaces/email/IOutboundEmailsDb";
import { OutboundEmailsDbPrisma } from "./repositories/prisma/OutboundEmailsDbPrisma";
import { ICreditsDb } from "./interfaces/subscriptions/ICreditsDb";
import { CreditsDbPrisma } from "./repositories/prisma/CreditsDbPrisma";
import { ISubscriptionProductsDb } from "./interfaces/subscriptions/ISubscriptionProductsDb";
import { SubscriptionProductsDbPrisma } from "./repositories/prisma/SubscriptionProductsDbPrisma";
import { ISubscriptionFeatureDb } from "./interfaces/subscriptions/ISubscriptionFeatureDb";
import { SubscriptionFeatureDbPrisma } from "./repositories/prisma/SubscriptionFeatureDbPrisma";
import { ICheckoutSessionsDb } from "./interfaces/subscriptions/ICheckoutSessionsDb";
import { CheckoutSessionsDbPrisma } from "./repositories/prisma/CheckoutSessionsDbPrisma";
import { ICheckoutSessionStatusDb } from "./interfaces/subscriptions/ICheckoutSessionStatusDb";
import { CheckoutSessionStatusDbPrisma } from "./repositories/prisma/CheckoutSessionStatusDbPrisma";
import { IPortalUsersDb } from "./interfaces/portals/IPortalUsersDb";
import { PortalUsersDbPrisma } from "./repositories/prisma/PortalUsersDbPrisma";
import { IPortalUserSubscriptionProductsDb } from "./interfaces/portals/IPortalUserSubscriptionProductsDb";
import { PortalUserSubscriptionProductsDbPrisma } from "./repositories/prisma/PortalUserSubscriptionProductsDbPrisma";
import { IPortalSubscriptionProductsDb } from "./interfaces/portals/IPortalSubscriptionProductsDb";
import { PortalSubscriptionProductsDbPrisma } from "./repositories/prisma/PortalSubscriptionProductsDbPrisma";
import { IPortalUserSubscriptionsDb } from "./interfaces/portals/IPortalUserSubscriptionsDb";
import { PortalUserSubscriptionsDbPrisma } from "./repositories/prisma/PortalUserSubscriptionsDbPrisma";
import { IPortalPagesDb } from "./interfaces/portals/IPortalPagesDb";
import { PortalPagesDbPrisma } from "./repositories/prisma/PortalPagesDbPrisma";
import { IPortalsDb } from "./interfaces/portals/IPortalsDb";
import { PortalsDbPrisma } from "./repositories/prisma/PortalsDbPrisma";
import { IPortalCheckoutSessionsDb } from "./interfaces/portals/IPortalCheckoutSessionsDb";
import { PortalCheckoutSessionsDbPrisma } from "./repositories/prisma/PortalCheckoutSessionsDbPrisma";
import { IIpAddressLogsDb } from "./interfaces/ipAddresses/IIpAddressLogsDb";
import { IpAddressLogsDbPrisma } from "./repositories/prisma/IpAddressLogsDbPrisma";
import { IIpAddressesDb } from "./interfaces/ipAddresses/IIpAddressesDb";
import { IpAddressesDbPrisma } from "./repositories/prisma/IpAddressesDbPrisma";
import { ILogsDb } from "./interfaces/logs/ILogsDb";
import { LogsDbPrisma } from "./repositories/prisma/LogsDbPrisma";
import { IAppPortalConfigurationDb } from "./interfaces/core/IAppPortalConfigurationDb";
import { AppPortalConfigurationDbPrisma } from "./repositories/prisma/AppPortalConfigurationDbPrisma";
import { IUserRolesDb } from "./interfaces/permissions/IUserRolesDb";
import { UserRolesDbPrisma } from "./repositories/prisma/UserRolesDbPrisma";
import { IRolesDb } from "./interfaces/permissions/IRolesDb";
import { RolesDbPrisma } from "./repositories/prisma/RolesDbPrisma";
import { IPermissionsDb } from "./interfaces/permissions/IPermissionsDb";
import { PermissionsDbPrisma } from "./repositories/prisma/PermissionsDbPrisma";
import { IRolePermissionsDb } from "./interfaces/permissions/IRolePermissionsDb";
import { RolePermissionsDbPrisma } from "./repositories/prisma/RolePermissionsDbPrisma";
import { IAppWidgetsConfigurationDb } from "./interfaces/core/IAppWidgetsConfigurationDb";
import { AppWidgetsConfigurationDbPrisma } from "./repositories/prisma/AppWidgetsConfigurationDbPrisma";
import { IApiKeysDb } from "./interfaces/apiKeys/IApiKeysDb";
import { ApiKeysDbPrisma } from "./repositories/prisma/ApiKeysDbPrisma";
import { ICampaignsDb } from "./interfaces/email/ICampaignsDb";
import { CampaignsDbPrisma } from "./repositories/prisma/CampaignsDbPrisma";
import { IEmailSenderDb } from "./interfaces/email/IEmailSenderDb";
import { EmailSenderDbPrisma } from "./repositories/prisma/EmailSenderDbPrisma";
import { IEmailAttachmentsDb } from "./interfaces/email/IEmailAttachmentsDb";
import { EmailAttachmentsDbPrisma } from "./repositories/prisma/EmailAttachmentsDbPrisma";
import { IEmailsDb } from "./interfaces/email/IEmailsDb";
import { EmailsDbPrisma } from "./repositories/prisma/EmailsDbPrisma";
import { IAnalyticsUniqueVisitorsDb } from "./interfaces/analytics/IAnalyticsUniqueVisitorsDb";
import { AnalyticsUniqueVisitorsDbPrisma } from "./repositories/prisma/AnalyticsUniqueVisitorsDbPrisma";

export type DatabaseOrm = "prisma";
export class Database {
  provider: DatabaseOrm | undefined;
  appConfiguration: IAppConfigurationDb;
  users: IUsersDb;
  userRegistrationAttempt: IUserRegistrationAttemptDb;
  tenant: ITenantsDb;
  tenantUser: ITenantUserDb;
  roles: IRolesDb;
  tenantIpAddress: ITenantIpAddressDb;

  appWidgetsConfiguration: IAppWidgetsConfigurationDb;
  rolePermissions: IRolePermissionsDb;
  permissions: IPermissionsDb;
  userRoles: IUserRolesDb;
  appPortalConfiguration: IAppPortalConfigurationDb;
  logs: ILogsDb;
  apiKeys: IApiKeysDb;
  ipAddresses: IIpAddressesDb;
  ipAddressLogs: IIpAddressLogsDb;
  portalCheckoutSessions: IPortalCheckoutSessionsDb;
  portals: IPortalsDb;
  portalPages: IPortalPagesDb;
  portalUserSubscriptions: IPortalUserSubscriptionsDb;
  portalSubscriptionProducts: IPortalSubscriptionProductsDb;
  portalUserSubscriptionProducts: IPortalUserSubscriptionProductsDb;
  portalUsers: IPortalUsersDb;
  checkoutSessions: ICheckoutSessionsDb;
  checkoutSessionStatus: ICheckoutSessionStatusDb;
  subscriptionProducts: ISubscriptionProductsDb;
  subscriptionFeature: ISubscriptionFeatureDb;
  credits: ICreditsDb;
  outboundEmails: IOutboundEmailsDb;
  promptFlowOutputMapping: IPromptFlowOutputMappingsDb;
  promptFlowInputVariables: IPromptFlowInputVariablesDb;
  promptFlows: IPromptFlowsDb;
  promptExecutions: IPromptExecutionsDb;
  promptFlowOutput: IPromptFlowOutputsDb;
  promptFlowGroups: IPromptFlowGroupsDb;
  pages: IPagesDb;
  pageMetaTags: IPageMetaTagsDb;
  pageBlocks: IPageBlocksDb;
  tenants: ITenantsDb;
  tenantUserInvitations: ITenantUserInvitationsDb;
  userGroups: IUserGroupsDb;
  tenantSubscriptions: ITenantSubscriptionsDb;
  blacklist: IBlacklistDb;
  tenantInboundAddresses: ITenantInboundAddressesDb;
  registration: IRegistrationDb;
  tenantSubscriptionProducts: ITenantSubscriptionProductsDb;
  tenantTypes: ITenantTypesDb;
  kbArticles: IKbArticlesDb;
  kbAnalytics: IKbAnalyticsDb;
  knowledgeBase: IKnowledgeBaseDb;
  kbCategorySections: IKbCategorySectionsDb;
  kbCategories: IKbCategoriesDb;
  onboardingSessions: IOnboardingSessionsDb;
  onboarding: IOnboardingDb;
  onboardingSessionStep: IOnboardingSessionStepsDb;
  eventWebhookAttempts: IEventWebhookAttemptsDb;
  events: IEventsDb;
  surveySubmissions: ISurveySubmissionsDb;
  surveys: ISurveysDb;
  feedback: IFeedbackDb;
  blog: IBlogDb;
  blogTags: IBlogTagsDb;
  blogCategories: IBlogCategoriesDb;
  featureFlags: IFeatureFlagsDb;
  entityGroups: IEntityGroupsDb;
  entities: IEntitiesDb;
  groups: IGroupsDb;
  rowTags: IRowTagsDb;
  rowPermissions: IRowPermissionsDb;
  rowRelationships: IRowRelationshipsDb;
  rowComments: IRowCommentsDb;
  rows: IRowsDb;
  entityTags: IEntityTagsDb;
  rowCommentReaction: IRowCommentReactionDb;
  entityWebhooks: IEntityWebhooksDb;
  entityTemplates: IEntityTemplatesDb;
  formulas: IFormulasDb;
  entityRelationships: IEntityRelationshipsDb;
  rowTasks: IRowTasksDb;
  entityViews: IEntityViewsDb;
  formulaLogs: IFormulaLogsDb;
  properties: IPropertiesDb;
  workflowBlocks: IWorkflowBlocksDb;
  workflowCredentials: IWorkflowCredentialsDb;
  workflowExecutions: IWorkflowExecutionsDb;
  workflowVariable: IWorkflowVariableDb;
  workflows: IWorkflowsDb;
  campaigns: ICampaignsDb;
  emailSenders: IEmailSenderDb;
  emailAttachments: IEmailAttachmentsDb;
  emails: IEmailsDb;
  analyticsUniqueVisitors: IAnalyticsUniqueVisitorsDb;

  constructor(provider?: DatabaseOrm) {
    let providerValue = provider || defaultAppConfiguration.app.orm;
    if (!providerValue) {
      throw new Error("provider is not defined. Valid values are: prisma");
    }
    // console.log("[TheRock] Using database ORM: " + providerValue);
    switch (providerValue) {
      case "prisma":
        this.provider = "prisma";
        this.appConfiguration = new AppConfigurationDbPrisma();
        this.users = new UsersDbPrisma();
        this.userRegistrationAttempt = new UserRegistrationAttemptDbPrisma();
        this.tenant = new TenantsDbPrisma();
        this.tenantUser = new TenantUserDbPrisma();
        this.tenantIpAddress = new TenantIpAddressDbPrisma();
        this.appWidgetsConfiguration = new AppWidgetsConfigurationDbPrisma();
        this.rolePermissions = new RolePermissionsDbPrisma();
        this.permissions = new PermissionsDbPrisma();
        this.roles = new RolesDbPrisma();
        this.userRoles = new UserRolesDbPrisma();
        this.appPortalConfiguration = new AppPortalConfigurationDbPrisma();
        this.logs = new LogsDbPrisma();
        this.apiKeys = new ApiKeysDbPrisma();
        this.ipAddresses = new IpAddressesDbPrisma();
        this.ipAddressLogs = new IpAddressLogsDbPrisma();
        this.portalCheckoutSessions = new PortalCheckoutSessionsDbPrisma();
        this.portals = new PortalsDbPrisma();
        this.portalPages = new PortalPagesDbPrisma();
        this.portalUserSubscriptions = new PortalUserSubscriptionsDbPrisma();
        this.portalSubscriptionProducts = new PortalSubscriptionProductsDbPrisma();
        this.portalUserSubscriptionProducts = new PortalUserSubscriptionProductsDbPrisma();
        this.portalUsers = new PortalUsersDbPrisma();
        this.checkoutSessions = new CheckoutSessionsDbPrisma();
        this.checkoutSessionStatus = new CheckoutSessionStatusDbPrisma();
        this.subscriptionProducts = new SubscriptionProductsDbPrisma();
        this.subscriptionFeature = new SubscriptionFeatureDbPrisma();
        this.credits = new CreditsDbPrisma();
        this.outboundEmails = new OutboundEmailsDbPrisma();
        this.promptFlowOutputMapping = new PromptFlowOutputMappingsDbPrisma();
        this.promptFlowInputVariables = new PromptFlowInputVariablesDbPrisma();
        this.promptFlows = new PromptFlowsDbPrisma();
        this.promptExecutions = new PromptExecutionsDbPrisma();
        this.promptFlowOutput = new PromptFlowOutputsDbPrisma();
        this.promptFlowGroups = new PromptFlowGroupsDbPrisma();
        this.pages = new PagesDbPrisma();
        this.pageMetaTags = new PageMetaTagsDbPrisma();
        this.pageBlocks = new PageBlocksDbPrisma();
        this.tenants = new TenantsDbPrisma();
        this.tenantUserInvitations = new TenantUserInvitationsDbPrisma();
        this.userGroups = new UserGroupsDbPrisma();
        this.tenantSubscriptions = new TenantSubscriptionsDbPrisma();
        this.blacklist = new BlacklistDbPrisma();
        this.tenantInboundAddresses = new TenantInboundAddressesDbPrisma();
        this.registration = new RegistrationDbPrisma();
        this.tenantSubscriptionProducts = new TenantSubscriptionProductsDbPrisma();
        this.tenantTypes = new TenantTypesDbPrisma();
        this.kbArticles = new KbArticlesDbPrisma();
        this.kbAnalytics = new KbAnalyticsDbPrisma();
        this.knowledgeBase = new KnowledgeBaseDbPrisma();
        this.kbCategorySections = new KbCategorySectionsDbPrisma();
        this.kbCategories = new KbCategoriesDbPrisma();
        this.onboardingSessions = new OnboardingSessionsDbPrisma();
        this.onboarding = new OnboardingDbPrisma();
        this.onboardingSessionStep = new OnboardingSessionStepsDbPrisma();
        this.eventWebhookAttempts = new EventWebhookAttemptsDbPrisma();
        this.events = new EventsDbPrisma();
        this.surveySubmissions = new SurveySubmissionsDbPrisma();
        this.surveys = new SurveysDbPrisma();
        this.feedback = new FeedbackDbPrisma();
        this.blog = new BlogDbPrisma();
        this.blogTags = new BlogTagsDbPrisma();
        this.blogCategories = new BlogCategoriesDbPrisma();
        this.featureFlags = new FeatureFlagsDbPrisma();
        this.entityGroups = new EntityGroupsDbPrisma();
        this.entities = new EntitiesDbPrisma();
        this.groups = new GroupsDbPrisma();
        this.rowTags = new RowTagsDbPrisma();
        this.rowPermissions = new RowPermissionsDbPrisma();
        this.rowRelationships = new RowRelationshipsDbPrisma();
        this.rowComments = new RowCommentsDbPrisma();
        this.rows = new RowsDbPrisma();
        this.entityTags = new EntityTagsDbPrisma();
        this.rowCommentReaction = new RowCommentReactionDbPrisma();
        this.entityWebhooks = new EntityWebhooksDbPrisma();
        this.entityTemplates = new EntityTemplatesDbPrisma();
        this.formulas = new FormulasDbPrisma();
        this.entityRelationships = new EntityRelationshipsDbPrisma();
        this.rowTasks = new RowTasksDbPrisma();
        this.entityViews = new EntityViewsDbPrisma();
        this.formulaLogs = new FormulaLogsDbPrisma();
        this.properties = new PropertiesDbPrisma();
        this.workflowBlocks = new WorkflowBlocksDbPrisma();
        this.workflowCredentials = new WorkflowCredentialsDbPrisma();
        this.workflowExecutions = new WorkflowExecutionsDbPrisma();
        this.workflowVariable = new WorkflowVariableDbPrisma();
        this.workflows = new WorkflowsDbPrisma();
        this.campaigns = new CampaignsDbPrisma();
        this.emailSenders = new EmailSenderDbPrisma();
        this.emailAttachments = new EmailAttachmentsDbPrisma();
        this.emails = new EmailsDbPrisma();
        this.analyticsUniqueVisitors = new AnalyticsUniqueVisitorsDbPrisma();

        break;
      default:
        throw new Error("Invalid defaultAppConfiguration.app.orm: " + providerValue + ". Valid values are: prisma");
    }
  }
}

let db = new Database();
export { db };
