import { redirect } from "next/navigation";
import { getServerTranslations } from "@/i18n/server";
import RowHelper from "@/lib/helpers/RowHelper";
import { createUserSession, getUserInfo } from "@/lib/services/session.server";
import HeaderBlock from "@/modules/pageBlocks/components/blocks/marketing/header/HeaderBlock";
import RowOverviewRoute from "@/modules/rows/components/RowOverviewRoute";
import { GetRowData, get, GetRelationshipRowsData, getRelationshipRows } from "@/utils/api/server/RowsApi";
import { Routes } from "@/utils/api/server/EntitiesApi";
import { getBaseURL } from "@/utils/url.server";
import ServerError from "@/components/ui/errors/ServerError";
import { IServerComponentsProps } from "@/lib/dtos/ServerComponentsProps";
import { db } from "@/db";

type PageData = {
  title: string;
  error?: string;
  publicRowData?: {
    rowData: GetRowData;
    routes: Routes;
    relationshipRows: GetRelationshipRowsData;
  };
};

async function getPageData(props: IServerComponentsProps): Promise<PageData> {
  const params = (await props.params) || {};
  const request = props.request!;
  const { t } = await getServerTranslations();
  const userInfo = await getUserInfo();
  if (userInfo.lightOrDarkMode === "dark") {
    await createUserSession(
      {
        ...userInfo,
        lightOrDarkMode: "light",
      },
      new URL(request.url).pathname
    );
  }

  const entity = await db.entities.getEntityBySlug({ tenantId: null, slug: params.entity!, activeOnly: true });
  const userId = (await getUserInfo()).userId;
  if (!entity.isAutogenerated || entity.type === "system") {
    throw redirect("/404?entity=" + params.entity);
  }
  try {
    const rowData = await get(params.id!, {
      entity,
      userId,
    });
    if (!rowData.rowPermissions.canRead) {
      throw Error(t(entity.title) + " is not public");
    }
    const xdata: PageData = {
      title: `${RowHelper.getTextDescription({ entity, item: rowData.item, t })} | ${process.env.APP_NAME}`,
      publicRowData: {
        rowData,
        routes: {
          publicUrl: getBaseURL() + `/public/:entity/:id`,
        },
        relationshipRows: await getRelationshipRows({ entity, tenantId: rowData.item.tenantId, userId }),
      },
    };
    return xdata;
  } catch (e: any) {
    return { title: "", error: e.message };
  }
}

export async function generateMetadata(props: IServerComponentsProps) {
  const data = await getPageData(props);
  return { title: data.title };
}

export default async function PublicRowItemRoute(props: IServerComponentsProps) {
  const { publicRowData, error } = await getPageData(props);
  const { t } = await getServerTranslations();
  return (
    <>
      <div>
        <div>
          <HeaderBlock />
          <div className="bg-background">
            <div className="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8">
              <div className="sm:align-center sm:flex sm:flex-col">
                <div className="relative mx-auto w-full max-w-7xl overflow-hidden px-2 py-12 sm:py-6">
                  {!publicRowData ? (
                    <>
                      <div className="text-center">
                        <h1 className="text-3xl font-extrabold tracking-tight sm:text-4xl">{t("shared.unauthorized")}</h1>
                        <p className="mt-4 text-lg leading-6 text-muted-foreground">{error}</p>
                      </div>
                    </>
                  ) : (
                    <>
                      <div className="text-center">
                        <h1 className="text-3xl font-extrabold tracking-tight sm:text-4xl">{t(publicRowData.rowData.entity.title)}</h1>
                        <p className="mt-4 text-lg leading-6 text-muted-foreground">
                          {publicRowData.rowData.item?.tenant ? (
                            <div>
                              {publicRowData.rowData.item?.tenant?.name}, {RowHelper.getRowFolio(publicRowData.rowData.entity, publicRowData.rowData.item)}
                            </div>
                          ) : (
                            <div>{RowHelper.getRowFolio(publicRowData.rowData.entity, publicRowData.rowData.item)}</div>
                          )}
                        </p>
                      </div>
                      <div className="mt-12">
                        <div className="space-y-3 border-2 border-dashed border-border bg-secondary p-6">
                          <RowOverviewRoute
                            rowData={publicRowData.rowData}
                            item={publicRowData.rowData.item}
                            routes={publicRowData.routes}
                            relationshipRows={publicRowData.relationshipRows}
                          />
                        </div>
                      </div>
                    </>
                  )}
                </div>
              </div>
            </div>
          </div>
        </div>
        <></>
      </div>
    </>
  );
}

export function ErrorBoundary() {
  return <ServerError />;
}
