"use server";

import { redirect } from "next/navigation";
import { getServerTranslations } from "@/i18n/server";
import { validateEntity } from "@/utils/api/server/EntitiesApi";
import { verifyUserHasPermission } from "@/lib/helpers/server/PermissionsService";
import * as Constants from "@/lib/constants";
import { clearAllCache } from "@/lib/services/cache.server";
import { db } from "@/db";

type ActionData = {
  error?: string;
  success?: string;
};

export async function createEntityAction(prevState: ActionData | null, formData: FormData): Promise<ActionData> {
  await verifyUserHasPermission("admin.entities.create");
  const { t } = await getServerTranslations();
  const action = formData.get("action")?.toString() ?? "";

  if (action === "create") {
    const name = formData.get("name")?.toString() ?? "";
    const slug = formData.get("slug")?.toString().toLowerCase() ?? "";
    const prefix = formData.get("prefix")?.toString() ?? "";
    const title = formData.get("title")?.toString() ?? "";
    const titlePlural = formData.get("title-plural")?.toString() ?? "";
    const isAutogenerated = Boolean(formData.get("is-autogenerated"));
    const hasApi = Boolean(formData.get("has-api"));
    const icon = formData.get("icon")?.toString() ?? "";
    const type = formData.get("type")?.toString() ?? "";
    const active = Boolean(formData.get("active"));

    const showInSidebar = Boolean(formData.get("show-in-sidebar"));
    const hasTags = Boolean(formData.get("has-tags"));
    const hasComments = Boolean(formData.get("has-comments"));
    const hasTasks = Boolean(formData.get("has-tasks"));
    const hasActivity = Boolean(formData.get("has-activity"));
    const hasBulkDelete = Boolean(formData.get("has-bulk-delete"));
    const hasViews = Boolean(formData.get("has-views"));

    const defaultVisibility = formData.get("default-visibility")?.toString() ?? Constants.DEFAULT_ROW_VISIBILITY;

    const onCreated = formData.get("onCreated")?.toString() ?? "redirectToOverview";
    const onEdit = formData.get("onEdit")?.toString() ?? "editRoute";

    const errors = await validateEntity({ tenantId: null, name, slug, order: null, prefix });
    if (errors.length > 0) {
      return { error: errors.join(", ") };
    }

    try {
      const entity = await db.entities.createEntity({
        name,
        slug,
        prefix,
        title,
        titlePlural,
        isAutogenerated,
        hasApi,
        icon,
        active,
        type,
        showInSidebar,
        hasTags,
        hasComments,
        hasTasks,
        hasActivity,
        hasBulkDelete,
        hasViews,
        defaultVisibility,
        onCreated,
        onEdit,
      });

      await db.permissions.createEntityPermissions(entity);

      await clearAllCache();

      if (entity) {
        redirect(`/admin/entities/${slug}/properties`);
      } else {
        return { error: "Could not create entity" };
      }
    } catch (e: any) {
      return { error: e.message };
    }
  } else {
    return { error: t("shared.invalidForm") };
  }
}
