import { EntityWithDetailsAndRelationshipsDto } from "@/db/models/entityBuilder/EntitiesModel";
import { Prisma, Entity } from "@prisma/client";
import { DefaultVisibility } from "@/lib/dtos/shared/DefaultVisibility";
import { EntityWithDetailsDto, EntityDto, EntityWithCountDto, RowsUsageDto } from "@/db/models/entityBuilder/EntitiesModel";
import { CreatePropertyDto } from "@/db/models/entityBuilder/PropertiesModel";

export interface IEntitiesDb {
  getEntitiesInIds(ids: string[]): Promise<EntityWithDetailsDto[]>;
  getAllEntities(tenantId: string | null, includeSystem?: boolean): Promise<EntityWithDetailsDto[]>;
  getAllEntitiesSimple({ active, types }: { active?: boolean; types?: string[] }): Promise<EntityDto[]>;
  getEntityDto({ id, name }: { id?: string; name?: string }): Promise<EntityDto | null>;
  getEntitiesByName(name: string[]): Promise<EntityDto[]>;
  getAllEntitiesWithRowCount({ tenantId }: { tenantId: string | null }): Promise<EntityWithCountDto[]>;
  getAllRowsUsage(tenantId: string): Promise<RowsUsageDto[]>;
  getEntityBySlug({ tenantId, slug, activeOnly }: { tenantId: string | null; slug: string; activeOnly?: boolean }): Promise<EntityWithDetailsDto>;
  getSimpleEntityBySlug(slug: string): Promise<EntityDto | null>;
  findEntityBySlug(slug: string): Promise<Entity | null>;
  getEntityById({ id, tenantId }: { id: string; tenantId: string | null | undefined }): Promise<EntityWithDetailsAndRelationshipsDto | null>;
  getEntityByName({ name, tenantId }: { name: string; tenantId: string | null | undefined }): Promise<EntityWithDetailsDto>;
  getEntityByIdOrName({ tenantId, id, name }: { tenantId: string | null | undefined; id?: string; name?: string }): Promise<EntityWithDetailsDto>;
  getEntityByIdNameOrSlug({ tenantId, idNameOrSlug }: { tenantId: string | null; idNameOrSlug: string }): Promise<EntityWithDetailsDto>;
  getEntityWithWhere({ tenantId, where }: { tenantId: string | null; where: Prisma.EntityWhereInput }): Promise<EntityWithDetailsAndRelationshipsDto | null>;
  createEntity(data: {
    name: string;
    slug: string;
    prefix: string;
    title: string;
    titlePlural: string;
    isAutogenerated: boolean;
    type: string;
    hasApi: boolean;
    icon: string;
    active: boolean;
    showInSidebar: boolean;
    hasTags: boolean;
    hasComments: boolean;
    hasTasks: boolean;
    hasActivity: boolean;
    hasBulkDelete: boolean;
    hasViews: boolean;
    defaultVisibility: string;
    onCreated: string | null;
    onEdit: string | null;
  }): Promise<Entity>;
  updateEntity(data: {
    id: string;
    name?: string;
    slug?: string;
    displayName?: string;
    description?: string | undefined;
    icon?: string | undefined;
    color?: string | undefined;
    order?: number;
    prefix?: string;
    title?: string;
    titlePlural?: string;
    isAutogenerated?: boolean;
    type?: string;
    hasApi?: boolean;
    active?: boolean;
    showInSidebar?: boolean;
    hasTags?: boolean;
    hasComments?: boolean;
    hasTasks?: boolean;
    hasActivity?: boolean;
    hasBulkDelete?: boolean;
    hasViews?: boolean;
    defaultVisibility?: DefaultVisibility | string;
    onCreated?: string | null;
    onEdit?: string | null;
    updatedById?: string;
  }): Promise<Entity | null>;
  deleteEntity(id: string, tenantId: string | null): Promise<Entity | null>;
  findEntityByName({ tenantId, name }: { tenantId: string | null; name: string }): Promise<EntityWithDetailsDto | null>;
  findSimpleEntityByName(name: string): Promise<{ id: string; title: string; titlePlural: string; slug: string } | null>;
  getEntityByPrefix(prefix: string): Promise<Entity | null>;
  createCoreEntity(
    data: {
      name: string;
      slug: string;
      title: string;
      titlePlural: string;
      prefix: string;
      type: string;
      isAutogenerated?: boolean;
      hasApi?: boolean;
      icon?: string;
      active?: boolean;
      showInSidebar?: boolean;
      hasTags?: boolean;
      hasComments?: boolean;
      hasTasks?: boolean;
      hasActivity?: boolean;
      hasBulkDelete?: boolean;
      hasViews?: boolean;
      defaultVisibility?: DefaultVisibility;
      onCreated?: string | null;
      onEdit?: string | null;
    },
    properties?: CreatePropertyDto[]
  ): Promise<Entity>;
  getMaxEntityOrder(): Promise<number>;
  getDefaultEntityVisibility(id: string): Promise<DefaultVisibility>;
  filterTenantId(
    tenantId: string | null | undefined
  ): Promise<{ tenantId?: string | null | undefined; OR?: { tenantId?: string | null | undefined }[] | undefined }>;
}
