import { redirect } from "next/navigation";
import * as Constants from "@/lib/constants";
import EntityForm from "@/components/entities/EntityForm";
import { getServerTranslations } from "@/i18n/server";
import { validateEntity } from "@/utils/api/server/EntitiesApi";
import { verifyUserHasPermission } from "@/lib/helpers/server/PermissionsService";
import { IServerComponentsProps } from "@/lib/dtos/ServerComponentsProps";
import { db } from "@/db";

export const action = async (props: IServerComponentsProps) => {
  const params = (await props.params) || {};
  const request = props.request!;
  await verifyUserHasPermission("admin.entities.update");
  const { t } = await getServerTranslations();

  const item = await db.entities.getEntityBySlug({ tenantId: null, slug: params.entity ?? "" });
  if (!item) {
    return redirect("/admin/entities");
  }

  const form = await request.formData();
  const action = form.get("action")?.toString() ?? "";
  if (action === "edit") {
    const name = form.get("name")?.toString() ?? "";
    const slug = form.get("slug")?.toString().toLowerCase() ?? "";
    const order = Number(form.get("order"));
    const prefix = form.get("prefix")?.toString() ?? "";
    const title = form.get("title")?.toString() ?? "";
    const titlePlural = form.get("title-plural")?.toString() ?? "";
    const isAutogenerated = Boolean(form.get("is-autogenerated"));
    const hasApi = Boolean(form.get("has-api"));
    const icon = form.get("icon")?.toString() ?? "";
    const active = Boolean(form.get("active"));
    const type = form.get("type")?.toString() ?? "";

    const showInSidebar = Boolean(form.get("show-in-sidebar"));
    const hasTags = Boolean(form.get("has-tags"));
    const hasComments = Boolean(form.get("has-comments"));
    const hasTasks = Boolean(form.get("has-tasks"));
    const hasActivity = Boolean(form.get("has-activity"));
    const hasBulkDelete = Boolean(form.get("has-bulk-delete"));
    const hasViews = Boolean(form.get("has-views"));

    const defaultVisibility = form.get("default-visibility")?.toString() ?? Constants.DEFAULT_ROW_VISIBILITY;

    const onCreated = form.get("onCreated")?.toString() ?? "redirectToOverview";
    const onEdit = form.get("onEdit")?.toString() ?? "editRoute";

    const errors = await validateEntity({ tenantId: null, name, slug, order, prefix, entity: item });
    if (errors.length > 0) {
      return Response.json({ error: errors.join(", ") }, { status: 400 });
    }

    try {
      await db.entities.updateEntity({
        id: item.id ?? "",
        name,
        slug,
        order,
        prefix,
        title,
        titlePlural,
        isAutogenerated,
        hasApi,
        icon,
        active,
        type,
        showInSidebar,
        hasTags,
        hasComments,
        hasTasks,
        hasActivity,
        hasBulkDelete,
        hasViews,
        defaultVisibility,
        onCreated,
        onEdit,
      });
      await db.permissions.deleteEntityPermissions(item);
      const updatedEntity = await db.entities.getEntityById({ tenantId: null, id: item.id });
      if (updatedEntity) {
        await db.permissions.createEntityPermissions(updatedEntity);
      }

      return redirect("/admin/entities");
    } catch (error: any) {
      return Response.json({ error: error.message }, { status: 400 });
    }
  } else {
    return Response.json({ error: t("shared.invalidForm") }, { status: 400 });
  }
};

export default async function EditEntityIndexRoute(props: IServerComponentsProps) {
  const params = (await props.params) || {};
  const request = props.request!;
  
  await verifyUserHasPermission("admin.entities.view");
  const item = await db.entities.getEntityBySlug({ tenantId: null, slug: params.entity ?? "" });
  
  if (!item) {
    redirect("/admin/entities");
  }

  return <EntityForm item={item} />;
}
