/* eslint-disable no-console */
import { PrismaClient } from "@prisma/client";

const prisma = new PrismaClient();

async function checkEntities() {
  const entities = await prisma.entity.findMany({
    select: {
      id: true,
      name: true,
      slug: true,
      title: true,
      isAutogenerated: true,
      showInSidebar: true,
    },
    orderBy: { order: "asc" },
  });

  console.log("\n📋 Admin Entities (tenantId: null):");
  console.log("=====================================");
  entities.forEach((entity) => {
    console.log(`
  Name: ${entity.name}
  Slug: ${entity.slug}
  Title: ${entity.title}
  Autogenerated: ${entity.isAutogenerated}
  Show in Sidebar: ${entity.showInSidebar}
  ID: ${entity.id}
    `);
  });

  await prisma.$disconnect();
}

checkEntities().catch((e) => {
  console.error(e);
  process.exit(1);
});
