import { db } from "../src/db";

async function testRoute() {
  try {
    console.log("\n🔍 Testing Route Access");
    console.log("=====================\n");

    // Check if companies entity exists
    const entity = await db.entities.getEntityBySlug({ tenantId: null, slug: "companies" });
    console.log("✅ Companies entity found:");
    console.log(`   ID: ${entity.id}`);
    console.log(`   Name: ${entity.name}`);
    console.log(`   Slug: ${entity.slug}`);
    console.log(`   Autogenerated: ${entity.isAutogenerated}`);
    console.log(`   Type: ${entity.type}`);

    // Check if admin user exists
    const adminUser = await db.users.getUserByEmail("admin@email.com");
    if (adminUser) {
      console.log("\n✅ Admin user found:");
      console.log(`   ID: ${adminUser.id}`);
      console.log(`   Email: ${adminUser.email}`);
      console.log(`   Admin: ${adminUser.admin}`);

      // Check permissions
      const hasPermission = await db.userRoles.countUserPermission(
        adminUser.id,
        null,
        "admin.entities.view"
      );
      console.log(`\n✅ Admin has entities.view permission: ${hasPermission > 0}`);
    } else {
      console.log("\n❌ Admin user not found");
    }

    console.log("\n✅ Route should work when authenticated!");
    console.log("\nTo test:");
    console.log("1. Open http://localhost:3000/login in your browser");
    console.log("2. Log in with: admin@email.com");
    console.log("3. Navigate to: http://localhost:3000/admin/entities/companies/no-code/__autogenerated/all-in-one");

  } catch (error) {
    console.error("\n❌ Error:", error);
  }
}

testRoute()
  .then(() => process.exit(0))
  .catch((error) => {
    console.error(error);
    process.exit(1);
  });
