/* eslint-disable no-console */
import { PrismaClient } from "@prisma/client";

const prisma = new PrismaClient();

async function testEntityFetch() {
  console.log("\n🔍 Testing Entity Fetch by Slug");
  console.log("=====================================\n");

  const slug = "company-sample";
  console.log(`Looking for entity with slug: "${slug}"`);

  // Try to fetch the entity the same way the page does
  const entity = await prisma.entity.findFirst({
    where: { slug },
    include: {
      properties: {
        orderBy: { order: "asc" }
      }
    }
  });

  if (!entity) {
    console.log("❌ Entity not found!");
    await prisma.$disconnect();
    return;
  }

  console.log("\n✅ Entity Found:");
  console.log(`   ID: ${entity.id}`);
  console.log(`   Name: ${entity.name}`);
  console.log(`   Slug: ${entity.slug}`);
  console.log(`   Title: ${entity.title}`);
  console.log(`   Type: ${entity.type}`);
  console.log(`   Is Autogenerated: ${entity.isAutogenerated}`);
  console.log(`   Has API: ${entity.hasApi}`);
  console.log(`   Active: ${entity.active}`);

  // Fetch rows
  const rows = await prisma.row.findMany({
    where: { entityId: entity.id },
    include: {
      values: true,
      sampleCustomEntity: true,
    }
  });

  console.log(`\n📊 Rows found: ${rows.length}`);

  if (rows.length > 0) {
    console.log("\n   First row:");
    console.log(`   - ID: ${rows[0].id}`);
    console.log(`   - Folio: ${rows[0].folio}`);
    console.log(`   - Values: ${rows[0].values.length}`);
    console.log(`   - Has sampleCustomEntity: ${!!rows[0].sampleCustomEntity}`);
  }

  console.log("\n✅ The entity can be fetched correctly!");
  console.log("\n📍 URL should work: http://localhost:3000/admin/entities/company-sample/no-code");

  await prisma.$disconnect();
}

testEntityFetch().catch((e) => {
  console.error(e);
  process.exit(1);
});
