/* eslint-disable no-console */
import { PrismaClient } from "@prisma/client";

const prisma = new PrismaClient();

async function updateCompanySample() {
  console.log("🔄 Updating Company - Sample entity to be autogenerated");
  
  const entity = await prisma.entity.findFirst({
    where: { slug: "company-sample" }
  });

  if (!entity) {
    console.log("❌ Company - Sample entity not found");
    await prisma.$disconnect();
    return;
  }

  await prisma.entity.update({
    where: { id: entity.id },
    data: { isAutogenerated: true }
  });

  console.log("✅ Company - Sample entity updated successfully");
  await prisma.$disconnect();
}

updateCompanySample().catch((e) => {
  console.error(e);
  process.exit(1);
});
