/* eslint-disable no-console */
import { PrismaClient } from "@prisma/client";

const prisma = new PrismaClient();

async function verifySetup() {
  console.log("\n🔍 Verifying Company - Sample Setup");
  console.log("=====================================\n");

  // Check entity
  const entity = await prisma.entity.findFirst({
    where: { slug: "company-sample" },
    include: {
      properties: {
        orderBy: { order: "asc" },
      },
    },
  });

  if (!entity) {
    console.log("❌ Entity not found!");
    await prisma.$disconnect();
    return;
  }

  console.log("✅ Entity Found:");
  console.log(`   Name: ${entity.name}`);
  console.log(`   Slug: ${entity.slug}`);
  console.log(`   Title: ${entity.title}`);
  console.log(`   Is Autogenerated: ${entity.isAutogenerated}`);
  console.log(`   Show in Sidebar: ${entity.showInSidebar}`);
  console.log(`   Properties: ${entity.properties.length}`);

  console.log("\n📝 Properties:");
  entity.properties.forEach((prop: any) => {
    console.log(`   - ${prop.name} (${prop.type})`);
  });

  // Check rows
  const rows = await prisma.row.findMany({
    where: { entityId: entity.id },
    include: {
      sampleCustomEntity: true,
      values: true,
    },
  });

  console.log(`\n📊 Rows: ${rows.length}`);
  rows.forEach((row: any) => {
    console.log(`\n   Row ID: ${row.id}`);
    console.log(`   Folio: ${row.folio}`);
    if (row.sampleCustomEntity) {
      console.log(`   Custom Text: ${row.sampleCustomEntity.customText}`);
      console.log(`   Custom Number: ${row.sampleCustomEntity.customNumber}`);
      console.log(`   Custom Boolean: ${row.sampleCustomEntity.customBoolean}`);
      console.log(`   Custom Select: ${row.sampleCustomEntity.customSelect}`);
    }
    console.log(`   Row Values: ${row.values.length}`);
  });

  console.log("\n✅ Verification complete!");
  console.log("\n📍 Access the no-code views at:");
  console.log(`   http://localhost:3000/admin/entities/no-code`);
  console.log(`   http://localhost:3000/admin/entities/company-sample/no-code`);

  await prisma.$disconnect();
}

verifySetup().catch((e) => {
  console.error(e);
  process.exit(1);
});
