import { FiltersDto } from "@/lib/dtos/data/FiltersDto";
import { PermissionsWithRolesDto } from "@/db/models/permissions/PermissionsModel";
import { Prisma } from "@prisma/client";

export interface IPermissionsDb {
  getAllPermissions(type?: string | undefined, filters?: FiltersDto | undefined): Promise<PermissionsWithRolesDto[]>;
  getAllPermissionsIdsAndNames(): Promise<
    {
      id: string;
      name: string;
    }[]
  >;
  getPermission(id: string): Promise<PermissionsWithRolesDto | null>;
  getPermissionByName(name: string): Promise<PermissionsWithRolesDto | null>;
  getPermissionName(name: string): Promise<{
    id: string;
    name: string;
    description: string;
  } | null>;
  getPermissionByNames(names: string[]): Promise<PermissionsWithRolesDto[]>;
  getNextPermissionsOrder(type?: string | undefined): Promise<number>;
  createPermissions(
    permissions: {
      inRoles: string[];
      name: string;
      description: string;
      type: string;
      entityId?: string | null | undefined;
    }[],
    fromOrder?: number
  ): Promise<void>;
  createPermission(data: { order: number; name: string; description: string; type: string; isDefault: boolean; entityId: string | null }): Promise<{
    name: string;
    id: string;
    createdAt: Date;
    updatedAt: Date;
    description: string;
    type: string;
    isDefault: boolean;
    order: number;
    entityId: string | null;
  }>;
  updatePermission(
    id: string,
    data: {
      name?: string | undefined;
      description?: string | undefined;
      type?: string | undefined;
      order?: number | undefined;
    }
  ): Promise<{
    name: string;
    id: string;
    createdAt: Date;
    updatedAt: Date;
    description: string;
    type: string;
    isDefault: boolean;
    order: number;
    entityId: string | null;
  }>;
  deletePermission(id: string): Promise<{
    name: string;
    id: string;
    createdAt: Date;
    updatedAt: Date;
    description: string;
    type: string;
    isDefault: boolean;
    order: number;
    entityId: string | null;
  }>;
  deleteEntityPermissions(entity: {
    name: string;
    id: string;
    createdAt: Date;
    updatedAt: Date;
    type: string;
    order: number;
    moduleId: string | null;
    slug: string;
    prefix: string;
    title: string;
    titlePlural: string;
    isAutogenerated: boolean;
    hasApi: boolean;
    icon: string;
    active: boolean;
    showInSidebar: boolean;
    hasTags: boolean;
    hasComments: boolean;
    hasTasks: boolean;
    hasActivity: boolean;
    hasBulkDelete: boolean;
    hasViews: boolean;
    defaultVisibility: string;
    onCreated: string | null;
    onEdit: string | null;
    promptFlowGroupId: string | null;
  }): Promise<Prisma.BatchPayload | undefined>;
  createEntityPermissions(entity: {
    name: string;
    id: string;
    createdAt: Date;
    updatedAt: Date;
    type: string;
    order: number;
    moduleId: string | null;
    slug: string;
    prefix: string;
    title: string;
    titlePlural: string;
    isAutogenerated: boolean;
    hasApi: boolean;
    icon: string;
    active: boolean;
    showInSidebar: boolean;
    hasTags: boolean;
    hasComments: boolean;
    hasTasks: boolean;
    hasActivity: boolean;
    hasBulkDelete: boolean;
    hasViews: boolean;
    defaultVisibility: string;
    onCreated: string | null;
    onEdit: string | null;
    promptFlowGroupId: string | null;
  }): Promise<void>;
  getAll(
    filters?:
      | {
          type?: string | undefined;
          roleId?: string | null | undefined;
        }
      | undefined
  ): Promise<PermissionsWithRolesDto[]>;
}
